# Generated by Django 6.0.2 on 2026-03-18 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fromnode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoingedges', to='network.node')),
                ('tonode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incomingedges', to='network.node')),
            ],
            options={
                'unique_together': {('fromnode', 'tonode')},
            },
        ),
    ]
