# Generated by Django 6.0.2 on 2026-03-20 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carpool', '0001_initial'),
        ('network', '0001_initial'),
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carpooloffer',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trips.trip'),
        ),
        migrations.AddField(
            model_name='carpoolrequest',
            name='dropoffnode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dropoffrequests', to='network.node'),
        ),
    ]
