# Generated by Django 6.0.2 on 2026-03-20 17:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carpool', '0002_initial'),
        ('network', '0001_initial'),
        ('trips', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='carpoolrequest',
            name='passenger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='carpoolrequest',
            name='pickupnode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickuprequests', to='network.node'),
        ),
        migrations.AddField(
            model_name='carpooloffer',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carpool.carpoolrequest'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trips.trip'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='wallet',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
