# Generated by Django 6.0.2 on 2026-03-29 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpool', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carpooloffer',
            name='detour',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='carpooloffer',
            name='fare',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='carpooloffer',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='carpoolrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
