# Generated by Django 6.0.2 on 2026-04-04 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpool', '0004_carpooloffer_detour_carpooloffer_fare_and_more'),
        ('trips', '0006_alter_triproute_trip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carpooloffer',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='carpool.carpoolrequest'),
        ),
        migrations.AlterField(
            model_name='carpooloffer',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='trips.trip'),
        ),
    ]
