# Generated by Django 6.0.2 on 2026-03-20 17:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('network', '0001_initial'),
        ('trips', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trip',
            name='endnode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tripend', to='network.node'),
        ),
        migrations.AddField(
            model_name='trip',
            name='startnode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tripstart', to='network.node'),
        ),
        migrations.AddField(
            model_name='triproute',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network.node'),
        ),
        migrations.AddField(
            model_name='triproute',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trips.trip'),
        ),
    ]
