# Generated by Django 6.0.2 on 2026-03-29 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_alter_trip_currentnode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='createdat',
            new_name='created_at',
        ),
    ]
