# Generated by Django 6.0.2 on 2026-03-29 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0004_rename_createdat_trip_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='triproute',
            options={'ordering': ['order']},
        ),
        migrations.RemoveField(
            model_name='trip',
            name='currentnode',
        ),
        migrations.AddField(
            model_name='trip',
            name='currentnodeindex',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='trip',
            name='maxpassengers',
            field=models.IntegerField(default=3),
        ),
    ]
