# Generated by Django 6.0.2 on 2026-03-29 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0005_alter_triproute_options_remove_trip_currentnode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triproute',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routenodes', to='trips.trip'),
        ),
    ]
